version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/let-it-ride:latest
    container_name: let-it-ride-app
    restart: always
    env_file: .env
    environment:
      SQLITE_PATH: /data/let-it-ride.sqlite
    networks:
      - app
    volumes:
      - sqlite-data:/data

  app-dev:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/let-it-ride:latest
    container_name: let-it-ride-app-dev
    restart: always
    command:
      - deno
      - run
      - --watch
      - -A
      - src/app.ts
    env_file: .env
    environment:
      SQLITE_PATH: /data/let-it-ride.sqlite
    networks:
      - app
    volumes:
      - ./src:/app/src:Z
      - ./locales:/app/locales:Z
      - ./deno.json:/app/deno.json:Z
      - ./deno.lock:/app/deno.lock:Z
      - deno-dir:/deno-dir
      - sqlite-data:/data

volumes:
  deno-dir:
    name: let-it-ride-deno-dir
  sqlite-data:
    name: let-it-ride-sqlite-data

networks:
  app:
    name: let-it-ride-app
