version: "3.8"

services:
  mongodb:
    image: docker.io/mongo:8
    container_name: let-it-ride-mongodb
    restart: always
    logging:
      driver: "none"
    command:
      - mongod
      - --quiet
    volumes:
      - mongodb-data:/data/db
    networks:
      - app
    ports:
      - "127.0.0.1:3001:27017"
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 1s

  app:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/let-it-ride:latest
    container_name: let-it-ride-app
    restart: always
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/let-it-ride
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app

  app-dev:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/let-it-ride:latest
    container_name: let-it-ride-app-dev
    restart: always
    command:
      - deno
      - run
      - --watch
      - -A
      - src/app.ts
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/let-it-ride
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app
    volumes:
      - ./src:/app/src:Z
      - ./locales:/app/locales:Z
      - ./deno.json:/app/deno.json:Z
      - ./deno.lock:/app/deno.lock:Z
      - deno-dir:/deno-dir

volumes:
  deno-dir:
    name: let-it-ride-deno-dir
  mongodb-data:
    name: let-it-ride-mongodb-data

networks:
  app:
    name: let-it-ride-app
